<a href="https://colab.research.google.com/github/michvic/processo-seletivo-LCC---etapa-2/blob/master/Edital_02_2020_Etapa_2_Resposta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# README

Para executar esse notebook no colab basta colocar os arquivos .csv no seu drive e passar o path para a variável.

Se você está executando de maneira local passe o caminho do diretório que o arquivo se encontra.

```
dasets_path = "Caminho do arquivo/file.csv"
```

# OBS
  Para executar sem a etapa de normalização apenas pule a célula "preprocessing"



In [0]:
from google.colab import drive

drive.mount('/content/gdrive')


Mounted at /content/gdrive


# load database




In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from os import path
from math import e


dasets_path = '/content/gdrive/My Drive/CienciaDeDados/'


# labels_ecg = pd.read_csv(path.join(dasets_path, 'labels_ecg.csv'), names=['label'])
# base_ecg = pd.read_csv(path.join(dasets_path, 'base_ecg.csv'),  )

# dataset
labels_ecg = np.genfromtxt(path.join(dasets_path, 'labels_ecg.csv'),delimiter=',')
labels_ecg = np.expand_dims(labels_ecg, axis=1)
base_ecg = np.genfromtxt(path.join(dasets_path, 'base_ecg.csv'),delimiter=',')

print("Shape data ",labels_ecg.shape)
print("Shape label " ,base_ecg.shape)


Shape data  (1000, 1)
Shape label  (1000, 1025)


# preprocessing

In [0]:
sum = 0

for i in range(base_ecg.shape[0]):
    # reduction of gain | g = 2.52e − 5
    base_ecg[i,:] = base_ecg[i,:] / 2.52*e - 5

    # reduction of constant component
    sum = sum + base_ecg[i,:]
    # rescaling
    base_ecg[i,:] = (base_ecg[i,:] - np.amin(base_ecg[i,:])) / (np.amax(base_ecg[i,:]) - np.amin(base_ecg[i,:]))

u = sum/base_ecg.shape[0]
print('ok!')

ok!


# train and test split

In [0]:

x_train, x_test, y_train, y_test = train_test_split(base_ecg, labels_ecg, test_size=0.3, random_state=0)

print('x_train shape:', x_train.shape)
print('y_train shape:', y_train.shape)
print('x_test shape:', x_test.shape)
print('y_test shape:', y_test.shape)


# Normalize data.
# x_train = x_train.astype('float32') / 255
# x_test = x_test.astype('float32') / 255

x_train shape: (700, 1025)
y_train shape: (700, 1)
x_test shape: (300, 1025)
y_test shape: (300, 1)


# SVM

In [0]:
# from sklearn.svm import SVC
from sklearn.svm import NuSVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score



model = NuSVC(kernel='rbf',nu=0.05)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("acc:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


acc: 0.82
[[70  2  0  0  0  0  3  0  0  0  1  0  0  0  0  0  0]
 [ 5 12  0  1  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  6  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  2 38  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0]
 [ 5  0  0  2  0  0 27  0  3  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  3 13  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0  0  0  1  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0  1  0  1  0  0  0]
 [ 1  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  1  0  0  0  0  0  0  0  0  0 29  0  0  2]
 [ 2  1  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 21]]
              precision    recall  f1-score   support

         1.0    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# kNN

In [0]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

model = KNeighborsClassifier(n_neighbors=1, metric='minkowski')

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("acc:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


acc: 0.82
[[70  2  0  0  0  0  3  0  0  0  1  0  0  0  0  0  0]
 [ 1 14  0  1  1  0  1  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  6  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  1  1 36  0  0  1  2  0  0  0  0  1  0  0  0  0]
 [ 1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  1  0  6  0  0  0  0  0  0  0  0  0  0  0]
 [ 4  0  0  2  0  0 26  3  2  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2 13  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  1  2  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  1  0  0  0  0  0  0  0  0  0 31  0  0  0]
 [ 1  1  0  1  0  0  0  0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 21]]
              precision    recall  f1-score   support

         1.0    